# main
PIPELINE_NAME: DeepLab

DIRECTORY:
  ROOT_DIRECTORY: /workspace/logs/ee543/baseline
  DATA_DIRECTORY: /workspace/dataset/
  LOGGER_DIRECTORY: log/baseline

SEED: 2019
DEVICE: cuda
DEVICE_LIST: [0]
WORKERS: 10

MODEL:
  PY: segmentation_models_pytorch.unet
  CLASS: Unet
  ARGS:
      encoder_name: resnet50
      encoder_weights: imagenet
      decoder_use_batchnorm: True
      decoder_channels: (256, 128, 64, 32, 16)
      classes: 2
      activation: None
      center: True

FOLD:
  NUMBER: 1
  USEFOLDS: [0]

# preprocessing
USE_SAMPLER: False

TRANSFORMS:
  TRAIN: transforms/train_simple_transforms.json
  VALID: transforms/valid_transforms.json

# training
CRITERION:
  NAME: CrossEntropyLoss
  ARGS:
    weight: [1, 10]

OPTIMIZER:
  CLASS: Adam
  ARGS:
    lr: 0.01
    weight_decay: 0.000005

SCHEDULER:
  CLASS: ReduceLROnPlateau
  ARGS:
    mode: max
    factor: 0.1
    patience: 5
    threshold: 0.0000001
    min_lr: 0.0000001


BATCH_SIZE: 10
ACCUMULATION_STEP: 2
EPOCHS: 200
EARLY_STOPPING: 60

# saving
CHECKPOINTS:
  FULL_FOLDER: checkpoints
  BEST_FOLDER: checkpoints
  TOPK: 3

# validation
EVALUATION:
  SEARCH_PAIRS: [[0.3], [0.5], [0.7], [0.9]]