# main
PIPELINE_NAME: DeepLab

DIRECTORY:
  ROOT_DIRECTORY: /workspace/logs/ee543/baseline
  DATA_DIRECTORY: /workspace/dataset/VOCdevkit/VOC2012/
  LOGGER_DIRECTORY: log/friend_label3

SEED: 2019
DEVICE: cuda
#DEVICE_LIST: [0, 1]
WORKERS: 10

MODEL1:
  PY: modeling.deeplab
  CLASS: DeepLab
  ARGS:
      num_classes: 21
      backbone: resnet
      output_stride: 16
      sync_bn: False
      freeze_bn: False
  pretrain: none
#  pretrain: /workspace/logs/ee543/baseline/log/baseline/checkpoints/DeepLab_fold0.pth

MODEL2:
  PY: modeling.deeplab
  CLASS: DeepLab
  ARGS:
      num_classes: 21
      backbone: resnet
      output_stride: 16
      sync_bn: False
      freeze_bn: False
  pretrain: none
#  pretrain: /workspace/logs/ee543/baseline/log/baseline/checkpoints/DeepLab_fold0.pth

FOLD:
  NUMBER: 1
  USEFOLDS: [0]

# preprocessing
USE_SAMPLER: False

# training
CRITERION:
  weight:
  size_average: True
  batch_average: True
  ignore_index: 255
  mode: ce
  cuda: True
#  ARGS:
#    weight: [1, 10]

OPTIMIZER:
  CLASS: SGD
  ARGS:
    momentum: 0.9
    weight_decay: 0.0005
    nesterov: False
    lr: 0.07

#OPTIMIZER:
#  CLASS: RAdam
#  ARGS:
#    lr: 0.03
#    weight_decay: 0.0005

SCHEDULER:
  CLASS: MultiStepLR
  ARGS:
    milestones: [10, 20, 40]
    gamma : 0.1

BATCH_SIZE: 8
ACCUMULATION_STEP: 2
EPOCHS: 40
EARLY_STOPPING: 40

# saving
CHECKPOINTS:
  FULL_FOLDER: checkpoints
  BEST_FOLDER: checkpoints
  TOPK: 3

# validation
EVALUATION:
  NUM_CLASSES: 21